### ISSUE TITLE
special page operand is treated as being in the zero page when traversing

### ISSUE THREAD

**Issue by ksherlock** [mnaberez/m740dasm#2]
should probably set `sp_addr` to the to `0xff00 | operands[0]`

https://github.com/mnaberez/m740dasm/blob/b2e29bdbb1763f33934027ef359e9077a4e8e8f5/m740dasm/disasm.py#L114-L115

and adjust the formatting here (to simply `0x%04x`)

https://github.com/mnaberez/m740dasm/blob/b2e29bdbb1763f33934027ef359e9077a4e8e8f5/m740dasm/disasm.py#L51

**Comment by ksherlock** [comment]
also, add `sp_addr` to the `target_address` list:

https://github.com/mnaberez/m740dasm/blob/b2e29bdbb1763f33934027ef359e9077a4e8e8f5/m740dasm/disasm.py#L65

**Comment by mnaberez** [comment]
Thanks for reporting these issues related to the Special Page.  I believe I've fixed this in 0e245beb7d7efe18ed5d18ba9b1e96e8643a4b25.  

Since I don't have a real firmware that uses Special Page, I added it to the end-to-end test program:

https://github.com/mnaberez/m740dasm/blob/0e245beb7d7efe18ed5d18ba9b1e96e8643a4b25/m740dasm/tests/end_to_end/testprog.asm#L40

The resulting disassembly now shows `0xff80` as code.
